name: Sync Coding Platforms Activity
on:
  schedule:
    - cron: "0 */6 * * *" # Runs completely hands-free every 6 hours
  workflow_dispatch: # Allows manual click-to-update refresh

jobs:
  sync-activities:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Fetch and Inject External Platform Submissions
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-username: "Pavithran_25"
          # This securely updates your local Git tree with a mini-commit 
          # whenever you solve outside challenges, automatically lighting up your main grid.
